### PR TITLE
Update to current rust stable

### PR DESCRIPTION
**Pull request by juanibiapina**

### CODE REVIEW

**Comment by acmiyaguchi** [comment]
Sweet, thanks for updating rust-tinywm to modern rust. 

Quick question before I merge in your changes. I pulled a local copy of your branch to my machine, but I can't seem to get the left/right clicks to work as expected. Does it run as expected on your machine?

**Comment by juanibiapina** [comment]
I think so. I can test it again but my hard drive failed so it might take a few days.

**Comment by juanibiapina** [comment]
@acmiyaguchi I don't see any problems. What do you see?

**Comment by acmiyaguchi** [comment]
I reviewed it on another machine, it seemed to just be my VM acting up with the input. Everything looks good, thanks!

**Pull request merged**
